<?php

namespace AppBundle\Repository;

/**
 * User_watchedVideoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserWatchedVideoRepository extends \Doctrine\ORM\EntityRepository
{
}
